[project]
name = "elt-retail-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.11.3",
    "dbt-postgres>=1.10.0",
    "faker>=40.1.2",
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
]
